language: node_js
sudo: false
node_js:
- '6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
services:
  - redis-server
cache:
  directories:
    - node_modules
script: npm test
env:
  global:
  - CXX=g++-4.8
