development:
  taskcluster:
    credentials:
      clientId: ...
      accessToken: ...
  pulse:
    username: ...
    password: ...
  influx:
    connectionString: ...
  sqs:
    accessKeyId: ...
    secretAccessKey: ...
  aws:
    accessKeyId: ...
    secretAccessKey: ...



